apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: diploma-app-ingress
  namespace: cicd
spec:
  ingressClassName: nginx
  rules:
    - host: your-domain.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devops-diplom-app
                port:
                  number: 80
